### PR TITLE
made changes in navbar, made sticky navbar,and styled it.

### PR DESCRIPTION
**Pull request by pankajsingh92533**
new devprofile

kindly review and merge it under tag hacktoberfest :)

### CODE REVIEW

**Comment by oyepriyansh** [comment]
it is messed up
image

**Comment by pankajsingh92533** [comment]
corrected one
i have corrected that as per suggestions,
kindly review it..

**Comment by oyepriyansh** [comment]
It is not responsive on mobile, and the search bar becomes too small when in the navbar.

**Comment by pankajsingh92533** [comment]
ss1
i have made responsive as per instruction ,kindly review it please.

**Comment by oyepriyansh** [comment]
It is not looking good.
Screenshot_2023-10-06-14-07-12-07_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by pankajsingh92533** [comment]
this is for smaller screen:->
ss1

this is for medium screen
ss2 for medium screen

this is for big screen
ss3 for big screen

customized as per instructions,
please review it.

**Comment by pankajsingh92533** [comment]
I have made the necessary changes,
Please review it.

**Comment by oyepriyansh** [comment]
i am sorry but this is very ugly and give a bad user experience

**Pull request closed without merging**
