### PR TITLE
Revamp Footer for Professional Look

### PR DESCRIPTION
**Pull request by dev31sanghvi**
here is the more cleaner layout :

Screenshot from 2024-01-19 20-57-43

### CODE REVIEW

**Comment by oyepriyansh** [comment]
There is a conflict in this branch since you raised the PR from the same branch as last time.
Also, we don't have a privacy policy, so don't include that link.

**Comment by dev31sanghvi** [comment]
@oyepriyansh  resolved that issue ..

**Comment by dev31sanghvi** [comment]
@oyepriyansh  hey priyansh ! i have pushed the changes from a whole different branch but still there is merge conflict.. can you help me out ?

**Comment by oyepriyansh** [comment]
no it was the same branch in which you pushed before 
https://github.com/dev31sanghvi/DevProfiles/branches

**Pull request closed without merging**
