### PR TITLE
Fixed/btn on hover

### PR DESCRIPTION
**Pull request by Neeraaaj**
fixed the issue of hovering the btn from light to dark 

dark mode 

dark

white mode 
white

### CODE REVIEW

**Comment by oyepriyansh** [comment]
on hover the light theme button is shown 

image

**Comment by Neeraaaj** [comment]
@oyepriyansh yes i thought the themes of button should be contradictory like in dark mode the button should be light on hover and vise versa with the light theme

**Comment by Neeraaaj** [comment]
@oyepriyansh should i keep the same and just fix the text issue?

**Comment by oyepriyansh** [comment]
just fix the text issue

**Pull request merged**
