### PR TITLE
chore: Added profile - shiv19

### PR DESCRIPTION
**Pull request by shiv19**

### CODE REVIEW

**Comment by oyepriyansh** [comment]
why u changed others formatting?

**Comment by shiv19** [comment]
that's what I'm currently investigating.
I used github's editor to make this commit.
But looks like you merged some PR 3 minutes ago.
but my fork is still saying that it is only ahead by 1 commit.
just wait until it gets resolved.

**Comment by oyepriyansh** [comment]
sync the repository and try commit again

**Comment by shiv19** [comment]
@oyepriyansh If you check your repo now, there are double ups for Rushikesh Shelar and Michael Ortiz,
Do you want me to clean it up in the same PR?

**Pull request closed without merging**
