### PR TITLE
Update index.html with my details

### PR DESCRIPTION
**Pull request by akshatmishra25**

### CODE REVIEW

**Comment by Atharvan2004** [comment]
can u please help me
my vercel deployment has been failing. What should I do?

**Comment by oyepriyansh** [comment]
fix conflicts

**Comment by oyepriyansh** [comment]
don't worry about vercel deployment as the todays deployment limit is reached
but yiu should fix conflicting files by syncing the repository and recommiting

**Comment by akshatmishra25** [comment]
What changes should I make to fix merge conflicts

**Comment by oyepriyansh** [comment]
> What changes should I make to fix merge conflicts

just sync your repositoryand commit your changes again

**Pull request closed without merging**
