### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jerrygood24**

### CODE REVIEW

**Comment by oyepriyansh** [comment]
Remove the brackets from the anchor tag while you replace the placeholders with actual url.

Screenshot_2023-10-04-10-18-37-86_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by jerrygood24** [comment]
> Remove the brackets from the anchor tag while you replace the placeholders with actual url.
> 
> Screenshot_2023-10-04-10-18-37-86_40deb401b9ffe8e1df2f1cc5ba480b12

Done

**Review by oyepriyansh — APPROVED** [review]

**Comment by oyepriyansh** [comment]
fix conflits, try adding your profile in between

**Comment by oyepriyansh** [comment]
still blocked because of conflicting files

**Comment by jerrygood24** [comment]
I will create a new pull request

**Pull request closed without merging**
