### PR TITLE
[Added] Added my profile (Rohan Dol)

### PR DESCRIPTION
**Pull request by rohandol112**
**Checklist**
                    1.Update html section

**Current Status** 
                   working fine ready to merge.
Please merged it as a hacktoberfest.

### CODE REVIEW

**Comment by rohandol112** [comment]
is anything mistake? is anything to do it get merge.

**Comment by rohandol112** [comment]
Resolved Merge Conflicts

**Comment by oyepriyansh** [comment]
> Resolved Merge Conflicts

Conflicts have been resolved, but the code you've changed doesn't add any profiles; instead, it removes someone's profile. Please check.

**Comment by rohandol112** [comment]
okay,sure i'll take a glance

**Comment by rohandol112** [comment]
Now every thing is fine,Able to merge

**Comment by oyepriyansh** [comment]
not yet
image

**Comment by rohandol112** [comment]
why this is happening can you please guide me?

**Comment by oyepriyansh** [comment]
> why this is happening can you please guide me?

because your repository is not synced to this repository

**Comment by rohandol112** [comment]
Now Fine

**Comment by oyepriyansh** [comment]
Please take a look, you have deleted vinay profile code snippet 
Screenshot_2023-10-05-13-10-14-53_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by oyepriyansh** [comment]
Bruh 

Screenshot_2023-10-05-14-07-34-23_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by rohandol112** [comment]
so sry for my mistakes.,i'm working and resolving why it happening.

**Comment by oyepriyansh** [comment]
> so sry for my mistakes.,i'm working and resolving why it happening.

It's fine bro, mistakes are the part of learning

**Pull request closed without merging**
