### PR TITLE
added myself :3c

### PR DESCRIPTION
**Pull request by rudy3333**
yeah

### CODE REVIEW

**Comment by rudy3333** [comment]
yeah we got a push going on between my commits brb

**Comment by oyepriyansh** [comment]
the PR is blocked from getting merged due to conflicting files, can you please sync to the main repository.

**Comment by rudy3333** [comment]
sure, im wokring on it RN

**Comment by rudy3333** [comment]
@oyepriyansh resolved :3

**Review by oyepriyansh — APPROVED** [review]

**Pull request merged**
