### PR TITLE
my profile added

### PR DESCRIPTION
**Pull request by SyntaxSmiler03**
@oyepriyansh, I've included my profile. Please provide feedback.
Thank you

### CODE REVIEW

**Comment by oyepriyansh** [comment]
please fix conflicts

**Comment by SyntaxSmiler03** [comment]
I'm working on it

**Review by oyepriyansh — APPROVED** [review]

**Comment by SyntaxSmiler03** [comment]
Hello @oyepriyansh,
I would appreciate your guidance on an issue I've encountered. I noticed that despite having the 'Hacktoberfest Accepted' tag, this PR seems to have been excluded from Hacktoberfest participation. Could you kindly explain the reasons behind this exclusion?

**Comment by oyepriyansh** [comment]
> Hello @oyepriyansh, I would appreciate your guidance on an issue I've encountered. I noticed that despite having the 'Hacktoberfest Accepted' tag, this PR seems to have been excluded from Hacktoberfest participation. Could you kindly explain the reasons behind this exclusion?

I don't have any idea about it, but maybe it's a caching issue. You can try waiting for some time and checking later on the Hacktoberfest website.

**Pull request merged**
