### PR TITLE
added profile

### PR DESCRIPTION
**Pull request by ChiragAgg5k**

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
Closes issue #45

**Review by oyepriyansh — APPROVED** [review]

**Comment by oyepriyansh** [comment]
fix conflicts

**Comment by oyepriyansh** [comment]
try adding your profile in between, instead of top and bottom

**Comment by ChiragAgg5k** [comment]
@oyepriyansh done

**Review by oyepriyansh — APPROVED** [review]

**Pull request merged**
