### PR TITLE
Added Contributing.md and updated readme file

### PR DESCRIPTION
**Pull request by ira-mane**
Hello , Please have a look on the contributing.md file and let me know any issue .
Thankyou !

### CODE REVIEW

**Comment by oyepriyansh** [comment]
it doesnt looks good

**Comment by ira-mane** [comment]
> it doesnt looks good

can you tell what changes do you need ?

**Comment by oyepriyansh** [comment]
you can check this repository readme and contributing file  https://github.com/oyepriyansh/DevTweet

**Comment by ira-mane** [comment]
> you can check this repository readme and contributing file https://github.com/oyepriyansh/DevTweet neat and clean

okay , I will make the necessary changes.

**Comment by ira-mane** [comment]
Please have a look to contributing.md file .

**Review by oyepriyansh — APPROVED** [review]

**Pull request merged**
