### PR TITLE
Profile 

### PR DESCRIPTION
**Pull request by hiteshverse**
#194profile
Hello @oyepriyansh.
I would really appreciate it if you can assign me this issue under the label "Hacktoberfest 2023".

### CODE REVIEW

**Comment by oyepriyansh** [comment]
adding profile will not count as a hacktoberfest contributions

**Review by WilliamDavidHarrison — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
As Priyansh said, we are not allowing adding a profile as a Hacktoberfest contribution.

**Comment by oyepriyansh** [comment]
> As Priyansh said, we are not allowing adding a profile as a Hacktoberfest contribution.

add a invalid label so the contribution will not count towards hacktoberfest

**Comment by oyepriyansh** [comment]
the invalid is temporary

**Pull request merged**
