### PR TITLE
data: profile addition by Ajay Dhangar

### PR DESCRIPTION
**Pull request by Ajay-Dhangar**

### CODE REVIEW

**Review by Ajay-Dhangar — COMMENTED** [review]
Now Check out

**Comment by oyepriyansh** [comment]
Please don't add your profile in top and bottom

**Comment by Ajay-Dhangar** [comment]
> Please don't add your profile in top and bottom

okay

**Review by Ajay-Dhangar — COMMENTED** [review]
I have updated

**Comment by oyepriyansh** [comment]
Merged in #208

**Pull request closed without merging**
