### PR TITLE
Add: my profile index.html

### PR DESCRIPTION
**Pull request by kanchanrai7**
Hey i have added my profile in this branch.
Please merge it in hackertober fest label.

### CODE REVIEW

**Comment by oyepriyansh** [comment]
what happened?

**Review by oyepriyansh — APPROVED** [review]

**Comment by oyepriyansh** [comment]
please fix merge conflicts

**Comment by oyepriyansh** [comment]
try adding your profile in between, not in top and bottom

**Comment by kanchanrai7** [comment]
Hey i have resolved all the conflicts please merge this PR under hacktoberfest label
Thanksss

**Review by oyepriyansh — APPROVED** [review]

**Pull request merged**
